# Build Vite and publish the dist folder
[build]
  command = "npm run build"
  publish = "dist"

# (Optional) Only keep this if you actually have serverless functions
#[functions]
#  directory = "netlify/functions"

# Single Page App routing (BrowserRouter)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Pin runtime to avoid surprise npm/node drift
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION  = "10"
