# This section provides the definitive build instructions for your Vite project.
[build]
  command = "npm run build"
  publish = "dist"

# This tells Netlify where to find your secure serverless functions.
[functions]
  directory = "netlify/functions"

# This is the crucial Single Page Application (SPA) redirect rule.
# It solves the "Page Not Found" error when you reload a page.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# This section uses the official Netlify plugin to solve the secrets scanning error.
# It uses the CORRECT package name for the plugin.
[[plugins]]
package = "netlify-plugin-secrets-scan"

  [plugins.inputs]
  # Use a wildcard to ignore all public Firebase keys.
  excludedKeys = ["VITE_FIREBASE_*"]
