# This section provides the definitive build instructions for your Vite project.
[build]
  command = "npm run build"
  publish = "dist"

# This tells Netlify where to find your secure serverless functions.
[functions]
  directory = "netlify/functions"

# This is the crucial Single Page Application (SPA) redirect rule.
# It solves the "Page Not Found" error when you reload a page.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# This section uses the official Netlify plugin to solve the final secrets scanning error.
# It directly implements the solution recommended by your last build log.
# It explicitly tells the scanner: "It is safe and expected for the Firebase
# client-side keys to be present in the final build output. Please ignore them."

  [plugins.inputs]
  # Use a wildcard to ignore all keys starting with VITE_FIREBASE_
  excludedKeys = ["VITE_FIREBASE_*"]
