# This section tells Netlify how to build your Vite project.
# It specifies the build command and the directory where the final files are placed.
[build]
  command = "npm run build"
  publish = "dist"

# This is the crucial Single Page App (SPA) redirect rule.
# It solves the "Page Not Found" error when you reload a page.
# It tells Netlify: "For any URL the user visits, if you can't find a file for it,
# just serve the main index.html file instead." Your React app will then handle the routing.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
